spring:
  config:
    import:
      - optional:file:.env
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}






