server:
  port: 8080

spring:
  config:
    import: "optional:file:.env[.properties]"
    activate:
      on-profile: local
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages
    encoding: UTF-8

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}
          max-tokens: ${OPENAI_MAXTOKENS}
  cloud:
    function:
      scan:
        enabled: false

hantu-openapi:
    appkey: ${HANTU_APPKEY}
    appsecret: ${HANTU_APPSECRET}
