server:
  port: 8080

spring:
  config:
    import: "optional:file:.env"
    activate:
      on-profile: local

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
          kakao:
            client-id: ${KAKAO_REST_CLIENT_ID}  # 카카오 개발자 콘솔에서 받은 REST API 키
            redirect-uri: ${KAKAO_REDIRECT_URI}  # 예: http://localhost:8080/auth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  messages:
    basename: messages
    encoding: UTF-8

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

hantu-openapi:
  appkey: ${HANTU_APPKEY}
  appsecret: ${HANTU_APPSECRET}
  base-url: https://openapi.koreainvestment.com:9443


db-openapi:
  db-appkey: ${DB_APPKEY}
  db-appsecret: ${DB_APPSECRET}
  base-url: https://openapi.dbsec.co.kr:8443

