server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
  main:
    web-application-type: reactive
  rsocket:
    server:
      transport: websocket
      port: 8082
      mapping-path: /rsocket

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

