name: CI/CD Pipeline

on:
  push:
    branches:
      - dev #실제 배포할 땐 main으로
      - feature/domain-setup  # 테스트용 추가

permissions:
  contents: read
  packages: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: .env 파일 만들기
        run: echo "${{secrets.ENV_VARS}}" > ./.env

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: Container Registry 서비스에 로그인
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 컨테이너 이미지 빌드 및 푸시
        run: |
          docker build -t ghcr.io/fintoryapp/fintory-server:latest -t ghcr.io/fintoryapp/fintory-server:${{ github.sha }} .
          docker push ghcr.io/fintoryapp/fintory-server:latest
          docker push ghcr.io/fintoryapp/fintory-server:${{ github.sha }}



