name: Fintory CI/CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
      branches: [ "dev" ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app-child: ${{ steps.filter.outputs.app-child }}
      app-parent: ${{ steps.filter.outputs.app-parent }}
      shared: ${{ steps.filter.outputs.shared }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app-child:
              - 'app-child/**'
            app-parent:
              - 'app-parent/**'
            shared:
              - 'auth/**'
              - 'domain/**'
              - 'common/**'
              - 'infra/**'
              - 'build.gradle'
              - 'settings.gradle'
              - 'gradle/**'

  build-and-deploy-child:
    needs: changes
    if: needs.changes.outputs.app-child == 'true' || needs.changes.outputs.shared == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: chmod +x ./gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push app-child
        run: |
          ./gradlew :app-child:clean :app-child:build
          docker build -t app-child:latest ./app-child
          docker tag app-child:latest ${{ steps.login-ecr.outputs.registry }}/fintory-child:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/fintory-child:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FINTORY_CHILD_HOST }}
          username: ubuntu
          timeout: 60s
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            export RDS_URL=${{ secrets.RDS_URL }}
            export RDS_USERNAME=${{ secrets.RDS_USERNAME }}
            export RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export ACCESS_TOKEN_EXPIRATION_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRATION_MINUTES }}
            export REFRESH_TOKEN_EXPIRATION_DAYS=${{ secrets.REFRESH_TOKEN_EXPIRATION_DAYS }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export KAKAO_REST_CLIENT_ID=${{ secrets.KAKAO_REST_CLIENT_ID }}
            export KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}
            export AWS_REDIS_PASSWORD=${{ secrets.AWS_REDIS_PASSWORD }}
            export ECOS_API_KEY=${{ secrets.ECOS_API_KEY}}
            
            aws ecr get-login-password --region ap-northeast-2 | \
              docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            docker pull ${{ steps.login-ecr.outputs.registry }}/fintory-child:latest

            docker compose down
            docker compose up -d

            docker image prune -f
            
